name: appcenter_example
description: Demonstrates how to use the appcenter plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  appcenter:
    path: ../src/appcenter

  appcenter_analytics:
    path: ../src/appcenter_analytics

  appcenter_crashes:
    path: ../src/appcenter_crashes

flutter:
  uses-material-design: true
